---
# vars file for install-monit-tools
url_repo_helm: https://charts.helm.sh/stable
url_repo_helm_2: https://prometheus-community.github.io/helm-charts
deploy_prometheus: " meu-querido-prometheus prometheus-community/kube-prometheus-stack"    
