- name: Download helm 
  get_url:
    url: "{{helm_url}}"
    dest: /tmp/get_helm.sh
    mode: 0755
  ignore_errors: true  
  register: dowload


- name: Instalando Helm
  shell:
    /tmp/get_helm.sh
  when:
    - dowload.failed|bool == false
  register: install_helm


- name: 
  debug: var=install_helm  
