- name: helm add repo
  shell: helm repo add stable {{url_repo_helm}}
  shell: helm repo add prometheus-community {{url_repo_helm_2}}
  register: prometheus_add_repo

- name: helm update
  shell: helm repo update
  register: prometheus_repo_update


- name: Instalando o prometheus community
  shell: helm install {{deploy_prometheus}}
  register: prometheus_install



